map_merge:
  ros__parameters:
    merging_rate: 1.0
    discovery_rate: 0.05
    estimation_rate: 0.5
    estimation_confidence: 0.6
    robot_map_topic: /map
    second_robot_map_topic: /robot_2/map
    robot_map_updates_topic: map_updates
    merged_map_topic: merge_map
    world_frame: map
    known_init_poses: true
    # known_init_poses: false

    # Define here robots' positions in the map if known_init_poses is true
    /map_merge/init_pose_x: 0.0
    /map_merge/init_pose_y: 0.0
    /map_merge/init_pose_z: 0.1
    /map_merge/init_pose_yaw: 0.0

    /robot_2/map_merge/init_pose_x: 0.0
    /robot_2/map_merge/init_pose_y: 1.0
    /robot_2/map_merge/init_pose_z: 0.1
    /robot_2/map_merge/init_pose_yaw: 0.0
